Ajout d'un connecteur à ExtractTableAPI
dataforgoodfr/12_taxobservatory pull request #7
Opened 2024-03-08 16:34 UTC by jeremyfix

Cette PR ajoute un petit connecteur qui permet d'interroger extracttable;

L'idée de cette PR est de garder la possibilité de repasser sur ExtractTable si on se rends compte que les autres outils ne marchent pas ; Disons rester sur la même chose que ce qu'utilisaient Giulia et Kane. 

Bien sûr, on va essayer de se passer du service payant de ExtractTable mais c'est histoire d'avoir une roue de secours; 

Si on veut tester le code, on peut se créer une clé gratuite qui donne 10 appels : https://extracttable.com/signup/trial.html

2024-03-11 15:40 UTC, RonanMorgan commented
tu peux corriger les conflits stp ?

2024-03-11 18:54 UTC, jeremyfix commented
J'ai corrigé les conflits;

Maintenant, le test ne passe pas à cause de pypdf2 qui a un problème remonté par la vérification de "safety":


```
+==============================================================================+
 VULNERABILITIES REPORTED 
+==============================================================================+

-> Vulnerability found in pypdf2 version 3.0.1
   Vulnerability ID: 59234
   Affected spec: >=2.2.0,<=3.0.1
   ADVISORY: Pypdf2 is vulnerable to CVE-2023-36464: An attacker may
   craft a PDF which leads to an infinite loop if '__parse_content_stream' is
   executed. That is, for example, the case if the user extracted text from
   such a PDF. Users may modify the line 'while peek not in (b"\r", b"\n")'
   in 'pypdf/generic/_data_structures.py' to 'while peek not in (b"\r",
   b"\n", b"")' as a workaround.https://github.com/py-
   pdf/pypdf/pull/1828https://github.com/py-
   pdf/pypdf/security/advisories/GHSA-4vvm-4w3v-6mr8
   CVE-2023-36464
   For more information about this vulnerability, visit
   https://data.safetycli.com/v/59234/97c
   To ignore this vulnerability, use PyUp vulnerability id 59234 in safety’s
   ignore command-line argument or add the ignore to your safety policy file.
```

la v3.0.1 est la dernière sortie, en décembre 2022;

Le problème c'est que extracttable a cette dépendance obsolète ; ils devraient passer à `pypdf` qui est le successeur de pypdf2 (voir la note https://pypi.org/project/PyPDF2/ )  mais une PR n'est pas intégrée :  https://github.com/ExtractTable/ExtractTable-py/pull/55

A la limite, comme cette interface à extracttable ne serait utile que pour conserver le pipeline utlisié précédemment mais ne sera peut être pas conservé au final ... je me demande si on ne devrait pas simplement ignorer cette PR pour le moment; voir au final , la ferme et ne pas l'intégrer.

2024-03-12 09:49 UTC, RonanMorgan commented
comme tu veux après franchement si c'est juste un problème de sécurité vu qu'on en est qu'au début du projet je me dit que c'est pas un drame, je peux merger

dit moi ce que tu préfères

2024-03-27 14:18 UTC, kaaloo requested changes
Nice work!  Unfortunately the API for calling the table extraction objects has changed.  It should be super quick to update your code.

2024-03-27 14:18 UTC, kaaloo commented on .env.example
> +EXTRACTABLE_API_KEY=CHANGE_ME
```suggestion
EXTRACT_TABLE_API_KEY=CHANGE_ME
```

2024-03-27 14:18 UTC, kaaloo commented on country_by_country/table_extraction/extract_table_api.py
> +        api_key = os.getenv("EXTRACTABLE_API_KEY")
```suggestion
        api_key = os.getenv("EXTRACT_TABLE_API_KEY")
```

2024-03-27 14:18 UTC, kaaloo commented on country_by_country/table_extraction/extract_table_api.py
> +    def __call__(self, pdf_filepath: str, assets: dict) -> None:
```suggestion
    def __call__(self, pdf_filepath: str) -> None:
```

The api for these table extractors has changed.  See the `unstructured_api` extractor.

2024-03-27 16:28 UTC, jeremyfix commented
@kaaloo  I fixed all the issues ; Thank your for your carefull review !  I tested it with my ExtractTable free API key , and it's working;

2024-04-10 19:56 UTC, merged