streamlit choose the parser
dataforgoodfr/12_taxobservatory pull request #79
Opened 2024-04-24 13:55 UTC by Qouentinne

2024-04-24 15:57 UTC, jeremyfix commented
quelques points : 

- :+1:  quand on importe une configuration yaml , la liste des parsers se met bien à jour
- [ ] :-1:  si on ne clique pas sur le bouton "Extract Tables" tout en bas de la sidebar, on peut quand même cliquer sur la page "Pages selection" et ça crash avec `'st.session_state has no key "assets"`

je ne sais pas ce qui est le mieux : le comportement d'avant était d'appliquer l'extraction dès lors qu'un rapport était uploadé . D'ailleurs, l'erreur `no key assets` n'est pas levée si on clique sur la page "Pages selection" sans uploader de rapport;

2024-04-24 19:58 UTC, RonanMorgan requested changes
=> si j'utilise le bouton de "load une config" ça ne fonctionne plus
![error](https://github.com/dataforgoodfr/12_taxobservatory/assets/49660557/eaeddfe2-8e57-4745-a4bd-738cf92d8ab5)

=> on ne peut pas choisir Extract Table

2024-04-25 07:42 UTC, Qouentinne commented on README.md
> -[PipelineDemonstration.webm](https://github.com/dataforgoodfr/12_taxobservatory/assets/1128418/f9c64e83-9c15-4de2-a512-4f4b25f2f3ae)
Pas du tout, c'est un truc que j'ai pas vu au moment de rebase 😅, je vais la remettre

2024-04-25 08:02 UTC, Qouentinne commented
> je ne sais pas ce qui est le mieux : le comportement d'avant était d'appliquer l'extraction dès lors qu'un rapport était uploadé . D'ailleurs, l'erreur `no key assets` n'est pas levée si on clique sur la page "Pages selection" sans uploader de rapport;

>     * la transition n'est pas automatique une fois l'upload du PDF, il faut penser à cliquer sur le bouton "Extract Tables" en bas de la sidebar

Je vais repasser à l'ancien comportement et passer la logique de choix des parsers sur la page suivante (selected_pages), ça me paraît plus logique en y reréfléchissant.

2024-04-25 13:53 UTC, RonanMorgan commented
t'as pas mis  Extract Table ? ça me semble important pasque Kane avait pas mal insisté sur le fait que selon son expérience c'était meilleur que les autres outils 

(par contre Camlelot et llamaparse à mon avis tu peux les enlever du choix par défaut

2024-04-25 16:30 UTC, Qouentinne commented
J'ai modifié les parsers par défaut. Par contre, je n'ai pas de clé API pour extracttable, j'ai suivi le readme.

2024-04-29 19:59 UTC, merged